<?php

declare(strict_types=1);

namespace ApiCore\Database\Attribute;

use ApiCore\Database\Enum\PrimaryKeyValue;

#[\Attribute(\Attribute::IS_REPEATABLE| \Attribute::TARGET_PROPERTY)]
class Primary
{
    public function __construct(
        private readonly PrimaryKeyValue $keyValue,
        private readonly bool $autogenerated = true
    ) {
    }

    public function getKeyValue(): PrimaryKeyValue
    {
        return $this->keyValue;
    }

    public function isAutogenerated(): bool
    {
        return $this->autogenerated;
    }
}
