<?php

declare(strict_types=1);

namespace ApiCoreTest\Dependency\Hook\Example;

use ApiCore\Dependency\Hook\BeforeConstruct\Attribute\BeforeConstruct;

class BeforeConstructExample
{
    private string $value;

    public function __construct(string $value = '')
    {
        $this->value = $value;
    }

    public function getValue(): string
    {
        return $this->value;
    }

    #[BeforeConstruct]
    public static function build(): BeforeConstructExample
    {
        return new self('Generated by beforeConstruct hook');
    }
}
